### ISSUE TITLE
In case crowdsale owner key has lost during ICO period.

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/tokyo#17]
1. Plz check owner authority.
2. What's going to happen if owner key have stolen or lost? Is it serious or not?
3. What is alternative or solution to that matters?
@4000D @thomashin

**Comment by ggs134** [comment]
![image 1](https://user-images.githubusercontent.com/8215282/39399546-a2b99128-4b5a-11e8-989b-83a6cc71474c.png)

**Comment by 4000D** [comment]
1. I think it's not a question.
2. cannot call `fianlize()` or `claimTokens()`. If owner's private key is lost, all Ether is locked in vault forever because sale cannot be finalized. Also tokens is going to be obsolete.

Actually, zeppelin-solidity adds `onlyOwner` modifier to `finalize()` function.
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/crowdsale/distribution/FinalizableCrowdsale.sol#L24

3. Multi-sig wallet is the exact solution in case of losing private key.

**Comment by 4000D** [comment]
Closing key management is out of scope
